"""Carpark table

Revision ID: 081e3590ddbe
Revises: 
Create Date: 2020-03-23 00:13:37.114615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081e3590ddbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_slot', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carpark_timestamp'), 'carpark', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carpark_timestamp'), table_name='carpark')
    op.drop_table('carpark')
    # ### end Alembic commands ###
